---
java_tar: jdk-8u121-linux-x64.tar.gz
java_name: jdk1.8.0_121
install_dir: /opt
tomcat_source: http://ftp.itu.edu.tr/Mirror/Apache/tomcat/tomcat-8/v8.0.43/bin
tomcat_tar: apache-tomcat-8.0.43.tar.gz
tomcat_version: apache-tomcat-8.0.43
jenkins_source: https://pkg.jenkins.io/redhat-stable/jenkins-2.7.4-1.1.noarch.rpm
jenkins_rpm: jenkins-2.7.4-1.1.noarch.rpm
