- hosts: maven1
  become: yes
  become_method: sudo
  tasks:
  - name: Variables
    include_vars: /home/ansible/roles/tomcat/vars/main.yml

  - name: Move jdk
    command: cp /home/ansible/{{ java_tar }} {{ install_dir }}

  - name: Extract archive
    unarchive: src={{ install_dir }}/{{ java_tar }} dest={{ install_dir }} remote_src=yes

  - name: Make Java available for system
    command: "{{ item }}"
    with_items:
    - alternatives --install /usr/bin/java java {{ install_dir }}/{{ java_name }}/bin/java 2
    - alternatives --install /usr/bin/jar jar {{ install_dir }}/{{ java_name }}/bin/jar 2
    - alternatives --install /usr/bin/javac javac {{ install_dir }}/{{ java_name }}/bin/javac 2
    - alternatives --set jar {{ install_dir }}/{{ java_name }}/bin/jar
    - alternatives --set javac {{ install_dir }}/{{ java_name }}/bin/javac

  - name: Set environment Variables
    shell: "{{ item }}"
    with_items:
    - export JAVA_HOME={{ install_dir }}/{{ java_name }}
    - export JRE_HOME={{ install_dir }}/{{ java_name }}/jre
    - export PATH=$PATH:{{ install_dir }}/{{ java_name }}/bin:{{ install_dir }}/{{ java_name }}/jre/bin

  - name: Download tomcat
    get_url: url={{ tomcat_source }}/{{ tomcat_tar }} dest={{ install_dir }}

  - name: Extract archive
    unarchive: src={{ install_dir }}/{{ tomcat_tar }} dest={{ install_dir }} remote_src=yes

  - name: Write tomcat startupscript to init.d
    template: src=/home/ansible/roles/tomcat/startupscript dest=/etc/init.d/tomcat8 mode=0755 owner=root backup=yes

  - name: Add to the tomcat-users.xml file
    lineinfile:
      dest={{ install_dir }}/{{ tomcat_version }}/conf/tomcat-users.xml
      state=present
      insertbefore=^</tomcat-users>
      line='<user username="oscarose" password="oscarose" roles="tomcat,admin-gui,manager-gui,manager-script"/>'

  - name: Make sure tomcat runs on boot, and start the service
    action: service name=tomcat8 enabled=yes state=started

  - name: Download jenkins
    get_url: url={{ jenkins_source }} dest={{ install_dir }}

  - name: install jenkins rpm
    yum:
      name: /opt/{{ jenkins_rpm }}
      state: present

  - name: start jenkins service
    action: service name=jenkins enabled=yes state=started
